version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
      - ./backup:/backup
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  app:
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${DOCKER_MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      JWT_COOKIE_EXPIRE: ${JWT_COOKIE_EXPIRE}
    ports:
      - "5000:5000"
    command: ["./scripts/wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

volumes:
  mongo-data:
